language: d
sudo: false

# Note: DMD v2.078.1-3 has a regression which makes std_data_json
# fails to compile
# This is why LDC v1.8.0 (FE 2.078.3) is not tested.
# Finally, LDC v1.7.0 (FE 2.077.1) is broken with:
# Integer arithmetic operators only work with integral types!
#   %6 = add i8* %4, %5, !dbg !5454
# LLVM ERROR: Broken function found, compilation aborted!

d:
  - dmd-2.090.0
  - dmd-2.088.1
  - dmd-2.087.1
  - dmd-2.086.1
  - dmd-2.085.1
  - dmd-2.084.1
  - dmd-2.083.1
  - dmd-2.082.1
  - dmd-2.081.1
  - ldc-1.20.0
  - ldc-1.18.0
  - ldc-1.17.0
  - ldc-1.16.0
  - ldc-1.15.0
  - ldc-1.14.0
  - ldc-1.13.0
  - ldc-1.12.0
  - ldc-1.11.0
  - dmd-beta

script:
  - dub test --compiler=${DC}
  - dub upgrade && dub test --compiler=${DC}

matrix:
  allow_failures:
    - d: dmd-beta
